use_frameworks!

platform :ios, '8.0'

target 'SGNetwork_Example' do
  pod 'SGNetwork', :path => '../'

  target 'SGNetwork_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
