#use_frameworks!

platform :ios, '8.0'

target 'SGNetwork_Example' do
  pod 'SGNetwork', :path => '../'
  pod 'SVProgressHUD', '~> 2.2.5'
  pod 'Masonry', '~> 1.1.0'
  
  
  target 'SGNetwork_Tests' do
    inherit! :search_paths

#    pod 'Specta'
#    pod 'Expecta'
#    pod 'FBSnapshotTestCase'
#    pod 'Expecta+Snapshots'
  end
end
